"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from plexus_flow._proto import worker_pb2 as _worker_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WorkerServiceStub:
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WorkerServiceAsyncStub: ...
    Connect: _grpc.StreamStreamMultiCallable[_worker_pb2.WorkerMessage, _worker_pb2.ServerMessage]

@_typing.type_check_only
class WorkerServiceAsyncStub(WorkerServiceStub):
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Connect: _aio.StreamStreamMultiCallable[_worker_pb2.WorkerMessage, _worker_pb2.ServerMessage]  # type: ignore[assignment]

class WorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    @_abc_1.abstractmethod
    def Connect(
        self,
        request_iterator: _MaybeAsyncIterator[_worker_pb2.WorkerMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_worker_pb2.ServerMessage], _abc.AsyncIterator[_worker_pb2.ServerMessage]]: ...

def add_WorkerServiceServicer_to_server(servicer: WorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
