"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _TaskKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TaskKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TaskKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TASK_KIND_ACTIVITY: _TaskKind.ValueType  # 0
    TASK_KIND_COMPENSATION: _TaskKind.ValueType  # 1
    """Compensation runs the compensating action of a completed step."""

class TaskKind(_TaskKind, metaclass=_TaskKindEnumTypeWrapper): ...

TASK_KIND_ACTIVITY: TaskKind.ValueType  # 0
TASK_KIND_COMPENSATION: TaskKind.ValueType  # 1
"""Compensation runs the compensating action of a completed step."""
Global___TaskKind: _TypeAlias = TaskKind  # noqa: Y015

@_typing.final
class WorkerMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTER_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    HEARTBEAT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def register(self) -> Global___Register: ...
    @_builtins.property
    def result(self) -> Global___TaskResult: ...
    @_builtins.property
    def heartbeat(self) -> Global___Heartbeat: ...
    def __init__(
        self,
        *,
        register: Global___Register | None = ...,
        result: Global___TaskResult | None = ...,
        heartbeat: Global___Heartbeat | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["heartbeat", b"heartbeat", "message", b"message", "register", b"register", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["heartbeat", b"heartbeat", "message", b"message", "register", b"register", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: _TypeAlias = _typing.Literal["register", "result", "heartbeat"]  # noqa: Y015
    _WhichOneofArgType_message: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___WorkerMessage: _TypeAlias = WorkerMessage  # noqa: Y015

@_typing.final
class ServerMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTERED_FIELD_NUMBER: _builtins.int
    TASK_FIELD_NUMBER: _builtins.int
    CANCEL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def registered(self) -> Global___Registered: ...
    @_builtins.property
    def task(self) -> Global___Task: ...
    @_builtins.property
    def cancel(self) -> Global___CancelTask: ...
    def __init__(
        self,
        *,
        registered: Global___Registered | None = ...,
        task: Global___Task | None = ...,
        cancel: Global___CancelTask | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cancel", b"cancel", "message", b"message", "registered", b"registered", "task", b"task"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cancel", b"cancel", "message", b"message", "registered", b"registered", "task", b"task"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_message: _TypeAlias = _typing.Literal["registered", "task", "cancel"]  # noqa: Y015
    _WhichOneofArgType_message: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_message) -> _WhichOneofReturnType_message | None: ...

Global___ServerMessage: _TypeAlias = ServerMessage  # noqa: Y015

@_typing.final
class Register(_message.Message):
    """Register must be the first message of a stream."""

    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    ACTIVITIES_FIELD_NUMBER: _builtins.int
    MAX_CONCURRENCY_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    max_concurrency: _builtins.int
    """Maximum number of tasks in flight. Zero means 1."""
    @_builtins.property
    def activities(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Activity names this worker can run. Compensating actions are activities too."""

    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        activities: _abc.Iterable[_builtins.str] | None = ...,
        max_concurrency: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activities", b"activities", "max_concurrency", b"max_concurrency", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Register: _TypeAlias = Register  # noqa: Y015

@_typing.final
class Registered(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEARTBEAT_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    heartbeat_interval_ms: _builtins.int
    """The worker must send a Heartbeat at least this often."""
    def __init__(
        self,
        *,
        heartbeat_interval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["heartbeat_interval_ms", b"heartbeat_interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Registered: _TypeAlias = Registered  # noqa: Y015

@_typing.final
class Heartbeat(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Heartbeat: _TypeAlias = Heartbeat  # noqa: Y015

@_typing.final
class Task(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DependencyOutputsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TASK_ID_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    STEP_NAME_FIELD_NUMBER: _builtins.int
    ACTIVITY_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    DEPENDENCY_OUTPUTS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    ATTEMPT_FIELD_NUMBER: _builtins.int
    TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """Identifies this delivery; echo it in TaskResult."""
    kind: Global___TaskKind.ValueType
    workflow_id: _builtins.str
    run_id: _builtins.str
    step_name: _builtins.str
    activity: _builtins.str
    input: _builtins.bytes
    attempt: _builtins.int
    """1-based attempt number of the step."""
    timeout_ms: _builtins.int
    """The task is cancelled by the server when this elapses; zero means no limit."""
    @_builtins.property
    def dependency_outputs(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Outputs of the steps this step depends on, by step name."""

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        kind: Global___TaskKind.ValueType = ...,
        workflow_id: _builtins.str = ...,
        run_id: _builtins.str = ...,
        step_name: _builtins.str = ...,
        activity: _builtins.str = ...,
        input: _builtins.bytes = ...,
        dependency_outputs: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        attempt: _builtins.int = ...,
        timeout_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activity", b"activity", "attempt", b"attempt", "dependency_outputs", b"dependency_outputs", "input", b"input", "kind", b"kind", "metadata", b"metadata", "run_id", b"run_id", "step_name", b"step_name", "task_id", b"task_id", "timeout_ms", b"timeout_ms", "workflow_id", b"workflow_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Task: _TypeAlias = Task  # noqa: Y015

@_typing.final
class CancelTask(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    reason: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelTask: _TypeAlias = CancelTask  # noqa: Y015

@_typing.final
class TaskResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    @_builtins.property
    def success(self) -> Global___Success: ...
    @_builtins.property
    def failure(self) -> Global___Failure: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        success: Global___Success | None = ...,
        failure: Global___Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "outcome", b"outcome", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "outcome", b"outcome", "success", b"success", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_outcome: _TypeAlias = _typing.Literal["success", "failure"]  # noqa: Y015
    _WhichOneofArgType_outcome: _TypeAlias = _typing.Literal["outcome", b"outcome"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_outcome) -> _WhichOneofReturnType_outcome | None: ...

Global___TaskResult: _TypeAlias = TaskResult  # noqa: Y015

@_typing.final
class Success(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OUTPUT_FIELD_NUMBER: _builtins.int
    output: _builtins.bytes
    def __init__(
        self,
        *,
        output: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["output", b"output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Success: _TypeAlias = Success  # noqa: Y015

@_typing.final
class Failure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    RETRYABLE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    """Machine-readable code, free-form and optional."""
    message: _builtins.str
    retryable: _builtins.bool
    """A retryable failure consumes one of the step's retries; a permanent one
    fails the step at once.
    """
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
        retryable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message", "retryable", b"retryable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Failure: _TypeAlias = Failure  # noqa: Y015
