# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from plexus_flow._proto import worker_pb2 as plexus__flow_dot___proto_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plexus_flow/_proto/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/plexusflow.worker.v1.WorkerService/Connect',
                request_serializer=plexus__flow_dot___proto_dot_worker__pb2.WorkerMessage.SerializeToString,
                response_deserializer=plexus__flow_dot___proto_dot_worker__pb2.ServerMessage.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=plexus__flow_dot___proto_dot_worker__pb2.WorkerMessage.FromString,
                    response_serializer=plexus__flow_dot___proto_dot_worker__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plexusflow.worker.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plexusflow.worker.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService lets activity workers run outside the plexus-flow process.

    A worker opens one Connect stream, announces the activities it can run, and
    then receives tasks and reports their results on the same stream. The server
    never sends more tasks than the worker's max_concurrency. Delivery is
    at-least-once: a task is redelivered if its worker disconnects, stops
    heartbeating or exceeds the step timeout, so activities must be idempotent.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/plexusflow.worker.v1.WorkerService/Connect',
            plexus__flow_dot___proto_dot_worker__pb2.WorkerMessage.SerializeToString,
            plexus__flow_dot___proto_dot_worker__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
