// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskKind int32

const (
	TaskKind_TASK_KIND_ACTIVITY TaskKind = 0
	// Compensation runs the compensating action of a completed step.
	TaskKind_TASK_KIND_COMPENSATION TaskKind = 1
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "TASK_KIND_ACTIVITY",
		1: "TASK_KIND_COMPENSATION",
	}
	TaskKind_value = map[string]int32{
		"TASK_KIND_ACTIVITY":     0,
		"TASK_KIND_COMPENSATION": 1,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Result
	//	*WorkerMessage_Heartbeat
	Message       isWorkerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Message() {}

func (*WorkerMessage_Result) isWorkerMessage_Message() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Message() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Registered
	//	*ServerMessage_Task
	//	*ServerMessage_Cancel
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServerMessage) GetTask() *Task {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *CancelTask {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type ServerMessage_Task struct {
	Task *Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *CancelTask `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*ServerMessage_Registered) isServerMessage_Message() {}

func (*ServerMessage_Task) isServerMessage_Message() {}

func (*ServerMessage_Cancel) isServerMessage_Message() {}

// Register must be the first message of a stream.
type Register struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Activity names this worker can run. Compensating actions are activities too.
	Activities []string `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	// Maximum number of tasks in flight. Zero means 1.
	MaxConcurrency int32 `protobuf:"varint,3,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *Register) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

type Registered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The worker must send a Heartbeat at least this often.
	HeartbeatIntervalMs int64 `protobuf:"varint,1,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *Registered) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies this delivery; echo it in TaskResult.
	TaskId     string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind       TaskKind `protobuf:"varint,2,opt,name=kind,proto3,enum=plexusflow.worker.v1.TaskKind" json:"kind,omitempty"`
	WorkflowId string   `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId      string   `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepName   string   `protobuf:"bytes,5,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Activity   string   `protobuf:"bytes,6,opt,name=activity,proto3" json:"activity,omitempty"`
	Input      []byte   `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	// Outputs of the steps this step depends on, by step name.
	DependencyOutputs map[string][]byte `protobuf:"bytes,8,rep,name=dependency_outputs,json=dependencyOutputs,proto3" json:"dependency_outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata          map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 1-based attempt number of the step.
	Attempt int32 `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// The task is cancelled by the server when this elapses; zero means no limit.
	TimeoutMs     int64 `protobuf:"varint,11,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_ACTIVITY
}

func (x *Task) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Task) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Task) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *Task) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *Task) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetDependencyOutputs() map[string][]byte {
	if x != nil {
		return x.DependencyOutputs
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTask) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TaskResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TaskResult_Success
	//	*TaskResult_Failure
	Outcome       isTaskResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOutcome() isTaskResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TaskResult) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *TaskResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*TaskResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isTaskResult_Outcome interface {
	isTaskResult_Outcome()
}

type TaskResult_Success struct {
	Success *Success `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type TaskResult_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*TaskResult_Success) isTaskResult_Outcome() {}

func (*TaskResult_Failure) isTaskResult_Outcome() {}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *Success) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type Failure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine-readable code, free-form and optional.
	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A retryable failure consumes one of the step's retries; a permanent one
	// fails the step at once.
	Retryable     bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *Failure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x14plexusflow.worker.v1\"\xd5\x01\n" +
	"\rWorkerMessage\x12<\n" +
	"\bregister\x18\x01 \x01(\v2\x1e.plexusflow.worker.v1.RegisterH\x00R\bregister\x12:\n" +
	"\x06result\x18\x02 \x01(\v2 .plexusflow.worker.v1.TaskResultH\x00R\x06result\x12?\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1f.plexusflow.worker.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"\xcc\x01\n" +
	"\rServerMessage\x12B\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2 .plexusflow.worker.v1.RegisteredH\x00R\n" +
	"registered\x120\n" +
	"\x04task\x18\x02 \x01(\v2\x1a.plexusflow.worker.v1.TaskH\x00R\x04task\x12:\n" +
	"\x06cancel\x18\x03 \x01(\v2 .plexusflow.worker.v1.CancelTaskH\x00R\x06cancelB\t\n" +
	"\amessage\"p\n" +
	"\bRegister\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"activities\x18\x02 \x03(\tR\n" +
	"activities\x12'\n" +
	"\x0fmax_concurrency\x18\x03 \x01(\x05R\x0emaxConcurrency\"@\n" +
	"\n" +
	"Registered\x122\n" +
	"\x15heartbeat_interval_ms\x18\x01 \x01(\x03R\x13heartbeatIntervalMs\"\v\n" +
	"\tHeartbeat\"\xbe\x04\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.plexusflow.worker.v1.TaskKindR\x04kind\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x1b\n" +
	"\tstep_name\x18\x05 \x01(\tR\bstepName\x12\x1a\n" +
	"\bactivity\x18\x06 \x01(\tR\bactivity\x12\x14\n" +
	"\x05input\x18\a \x01(\fR\x05input\x12`\n" +
	"\x12dependency_outputs\x18\b \x03(\v21.plexusflow.worker.v1.Task.DependencyOutputsEntryR\x11dependencyOutputs\x12D\n" +
	"\bmetadata\x18\t \x03(\v2(.plexusflow.worker.v1.Task.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\v \x01(\x03R\ttimeoutMs\x1aD\n" +
	"\x16DependencyOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\n" +
	"CancelTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa6\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x129\n" +
	"\asuccess\x18\x02 \x01(\v2\x1d.plexusflow.worker.v1.SuccessH\x00R\asuccess\x129\n" +
	"\afailure\x18\x03 \x01(\v2\x1d.plexusflow.worker.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"!\n" +
	"\aSuccess\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"U\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*>\n" +
	"\bTaskKind\x12\x16\n" +
	"\x12TASK_KIND_ACTIVITY\x10\x00\x12\x1a\n" +
	"\x16TASK_KIND_COMPENSATION\x10\x012h\n" +
	"\rWorkerService\x12W\n" +
	"\aConnect\x12#.plexusflow.worker.v1.WorkerMessage\x1a#.plexusflow.worker.v1.ServerMessage(\x010\x01B5Z3github.com/avivklas/plexus-flow/pkg/remote/workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_worker_proto_goTypes = []any{
	(TaskKind)(0),         // 0: plexusflow.worker.v1.TaskKind
	(*WorkerMessage)(nil), // 1: plexusflow.worker.v1.WorkerMessage
	(*ServerMessage)(nil), // 2: plexusflow.worker.v1.ServerMessage
	(*Register)(nil),      // 3: plexusflow.worker.v1.Register
	(*Registered)(nil),    // 4: plexusflow.worker.v1.Registered
	(*Heartbeat)(nil),     // 5: plexusflow.worker.v1.Heartbeat
	(*Task)(nil),          // 6: plexusflow.worker.v1.Task
	(*CancelTask)(nil),    // 7: plexusflow.worker.v1.CancelTask
	(*TaskResult)(nil),    // 8: plexusflow.worker.v1.TaskResult
	(*Success)(nil),       // 9: plexusflow.worker.v1.Success
	(*Failure)(nil),       // 10: plexusflow.worker.v1.Failure
	nil,                   // 11: plexusflow.worker.v1.Task.DependencyOutputsEntry
	nil,                   // 12: plexusflow.worker.v1.Task.MetadataEntry
}
var file_worker_proto_depIdxs = []int32{
	3,  // 0: plexusflow.worker.v1.WorkerMessage.register:type_name -> plexusflow.worker.v1.Register
	8,  // 1: plexusflow.worker.v1.WorkerMessage.result:type_name -> plexusflow.worker.v1.TaskResult
	5,  // 2: plexusflow.worker.v1.WorkerMessage.heartbeat:type_name -> plexusflow.worker.v1.Heartbeat
	4,  // 3: plexusflow.worker.v1.ServerMessage.registered:type_name -> plexusflow.worker.v1.Registered
	6,  // 4: plexusflow.worker.v1.ServerMessage.task:type_name -> plexusflow.worker.v1.Task
	7,  // 5: plexusflow.worker.v1.ServerMessage.cancel:type_name -> plexusflow.worker.v1.CancelTask
	0,  // 6: plexusflow.worker.v1.Task.kind:type_name -> plexusflow.worker.v1.TaskKind
	11, // 7: plexusflow.worker.v1.Task.dependency_outputs:type_name -> plexusflow.worker.v1.Task.DependencyOutputsEntry
	12, // 8: plexusflow.worker.v1.Task.metadata:type_name -> plexusflow.worker.v1.Task.MetadataEntry
	9,  // 9: plexusflow.worker.v1.TaskResult.success:type_name -> plexusflow.worker.v1.Success
	10, // 10: plexusflow.worker.v1.TaskResult.failure:type_name -> plexusflow.worker.v1.Failure
	1,  // 11: plexusflow.worker.v1.WorkerService.Connect:input_type -> plexusflow.worker.v1.WorkerMessage
	2,  // 12: plexusflow.worker.v1.WorkerService.Connect:output_type -> plexusflow.worker.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Heartbeat)(nil),
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Registered)(nil),
		(*ServerMessage_Task)(nil),
		(*ServerMessage_Cancel)(nil),
	}
	file_worker_proto_msgTypes[7].OneofWrappers = []any{
		(*TaskResult_Success)(nil),
		(*TaskResult_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
